site_name: Bump'X

# Repository
repo_name: datagouv/bumpx
repo_url: https://github.com/datagouv/bumpx

theme:
  name: material
  icon:
    logo: material/update

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra_css:
  - style.css

markdown_extensions:
  - meta
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings
  - include-markdown


nav:
  - Home: index.md
  - Usage:
    - Workflow: workflow.md
    - Configuration: rcfile.md
    - Hooks: hooks.md
    - Command line: commandline.md
  - Development:
    - API: api.md
    - Extending: extending.md
    - Contributing: contributing.md
    - Code of conduct: code-of-conduct.md
  - FAQ: faq.md
  - Changelog: changelog.md
